### ISSUE TITLE
Passing thru colliders, Straffing and automatic movement on grabbing an object and holding it close to your body and trying to move forward

### ISSUE THREAD

**Issue by chrisandrews10007** [ExtendRealityLtd/Tilia.Locomotors.AxisMove.Unity#35]
While holding an object close to your body I can pass thru other solid objects. If I move this object I am holding so that it is an arms length away from my body, then I wont pass thru solid objects, so I guess there is a bug in VRTK 4 that is causing this kind  of behavior. 
Also if a solid object has just one collider on it you can still pass thru it, so not sure why that is happening. I even increased the source thickness to 0.75. 
Also another weird thing I noticed when you place the  SolvedBodyCollisions() on the 'Diverged' Body event of Pseudobody is that as soon as you grab and object keeping the grabbed button pressed, you automatically start being pushed around in the world. 
On the other hand if you do not use the Diverged event on Pseudobody and instead go with using the  PositionChange() within the Movement Events for the various Locomotors.AxisMove abilities, then as soon as the object your holding touches your pseudo body, you start getting the weird straffing towards the left or Right movement when you try to move forward. 
I don't know if this happening because I am using Unity 2019.4.15f1 and Oculus Integration 20.1 as probably all this may be working with older versions of Unity and Oculus Integration, but ideally I believe it should work with any new version. 
I am using VRTK's CameraRigs.OculusIntegration.
Thanks,
Chris

**Comment by thestonefox** [comment]
You need to provide steps to reproduce and follow the template for raising a bug otherwise the ticket is closed until the template style is followed
